#!/bin/bash
echo "dependency check:"
pandoc=$(command -v pandoc)
context=$(command -v context)
qrencode=$(command -v qrencode)
if [ "$pandoc" = "/usr/bin/pandoc" ]; then
echo "pandoc: OK"
else
echo "pandoc: MISSING!"
echo "i refuse to continue until this is installed!"
exit
fi
if [ "$context" = "/usr/bin/context" ]; then
echo "context: OK"
else
echo "context: MISSING!"
echo "i refuse to continue until this is installed!"
exit
fi
if [ "$qrencode" = "/usr/bin/qrencode" ]; then
echo "qrencode: OK"
else
echo "qrencode: MISSING!"
echo "i refuse to continue until this is installed!"
exit
fi
sleep 1
printloc=/home/$USER/.afk/print.md
fileloc=/home/$USER/print.pdf
mkdir /home/$USER/.afk/
cd /home/$USER/.afk
echo "name:"
read name
echo "pronoun (he/she/they):"
read pronoun
echo "reason:"
read reason
echo "return time?"
read rtime
echo "tracker link:"
read tlink
echo "phone number:"
read phone
clear
echo "generating..."
if [ -n "$tlink" ]; then
echo "$tlink" | qrencode -o tlink.png
fi
if [ -n "$phone" ]; then
echo "tel:$phone" | qrencode -o phone.png
fi
echo "# $name isn't home at the moment." >> $printloc
if [ -n "$rtime" ]; then
echo "$pronoun'll be back at about $rtime." >> $printloc
fi
if [ -z "$rtime" ]; then
echo "$pronoun'll be back soon(ish)" >> $printloc
fi
echo "" >> $printloc
echo "" >> $printloc
if [ -n "$reason" ]; then
echo "The reason $pronoun listed is: '$reason'" >> $printloc
fi
if [ -n "$tlink" ]; then
echo "" >> $printloc
echo "" >> $printloc
echo "if you want to track $name, scan this:" >> $printloc

echo "" >> $printloc
echo "" >> $printloc
echo '![tracking link](tlink.png "if you see this, then nothing was supplied.")' >> $printloc
fi
if [ -n "$phone" ]; then
echo "" >> $printloc
echo "" >> $printloc
echo "if you wish to call or message $name, scan here:" >> $printloc
echo "" >> $printloc
echo "" >> $printloc
echo '![phone number](phone.png "qr code for phone number.")' >> $printloc
fi
echo "" >> $printloc
echo "" >> $printloc
echo "### " >> $printloc
echo "" >> $printloc
echo "" >> $printloc
printf "*Generated on: `date`, saved to $fileloc on system `hostname`, internal IP `hostname -I | cut -d' ' -f1`*" >> $printloc
echo "exporting..."
pandoc -o /home/$USER/print.pdf -f markdown -t context print.md
if [ "$1" = "-p" ]; then
echo "printing..."
echo "(this command-line option created with the assistance of James Tomasino (gopher://gopher.black) - cheers mate! :D"
echo "(this was wayy too easy xD)"
lp $fileloc
fi
echo "cleaning up..."
rm -rf /home/$USER/.afk/
echo "done."