#!/bin/bash
uuid=$(echo -n "`date --iso-8601 | sed s/-//g`" && echo -n "`date +"%T" | sed s/://g`")
echo "dependency check:"
pandoc=$(command -v pandoc)
wkhtmltopdf=$(command -v wkhtmltopdf)
qrencode=$(command -v qrencode)
printloc=/home/$USER/.afk/$uuid.md
fileloc=/home/$USER/print-$uuid.pdf
log=/home/$USER/afk-$uuid.log
if [ "$pandoc" = "/usr/bin/pandoc" ]; then
echo "pandoc: OK"
else
echo "pandoc: MISSING!"
echo "i refuse to continue until this is installed!"
exit
fi
if [ "$wkhtmltopdf" = "/usr/bin/wkhtmltopdf" ]; then
echo "wkhtmltopdf: OK"
else
echo "wkhtmltopdf: MISSING!"
echo "i refuse to continue until this is installed!"
exit
fi
if [ "$qrencode" = "/usr/bin/qrencode" ]; then
echo "qrencode: OK"
else
echo "qrencode: MISSING!"
echo "i refuse to continue until this is installed!"
exit
fi
sleep 1
clear
mkdir /home/$USER/.afk/
cd /home/$USER/.afk
echo "afk sign generator"
echo ""
echo -n "name: "
read name
echo -n "pronoun (he/she/they): "
read pronoun
echo -n "[OPTIONAL] reason: "
read reason
echo -n "[OPTIONAL] return time? "
read rtime
echo -n "[OPTIONAL] tracker link: "
read tlink
echo -n "[OPTIONAL] phone number: "
read phone
clear
echo "generating..."
if [ -n "$tlink" ]; then
echo "$tlink" | qrencode -o tlink.png
fi
if [ -n "$phone" ]; then
echo "tel:$phone" | qrencode -o phone.png
fi
echo "# $name isn't available at the moment." >> $printloc
if [ -n "$rtime" ]; then
echo "$pronoun'll be back at about $rtime." >> $printloc
fi
if [ -z "$rtime" ]; then
echo "$pronoun'll be back later." >> $printloc
fi
echo "" >> $printloc
echo "" >> $printloc
if [ -n "$reason" ]; then
echo "The reason $pronoun listed is: '$reason'" >> $printloc
fi
if [ -n "$tlink" ]; then
echo "" >> $printloc
echo "" >> $printloc
echo "if you want to track $name, scan this:" >> $printloc

echo "" >> $printloc
echo "" >> $printloc
echo '![tracking link](tlink.png "if you see this, then nothing was supplied.")' >> $printloc
fi
if [ -n "$phone" ]; then
echo "" >> $printloc
echo "" >> $printloc
echo "if you wish to call or message $name, scan here:" >> $printloc
echo "" >> $printloc
echo "" >> $printloc
echo '![phone number](phone.png "qr code for phone number.")' >> $printloc
fi
echo "" >> $printloc
echo "" >> $printloc
echo "### " >> $printloc
echo "" >> $printloc
echo "" >> $printloc
printf "*Generated on: `date --iso-8601` at `date +%T`, saved to $fileloc on system `hostname`, internal IP `hostname -I | cut -d' ' -f1`*" >> $printloc
echo "" >> $printloc
echo "" >> $printloc
echo -n "exporting... ["
pandoc -t html $uuid.md -o $fileloc --metadata pagetitle="made with afk sign generator" &> $log
echo "exported to $fileloc!]"
if [ "$1" = "-p" ]; then
echo "printing..."
echo "(this command-line option created with the assistance of James Tomasino (gopher://gopher.black) - cheers mate! :D"
echo "(this was wayy too easy xD)"
lp $fileloc
fi
echo "cleaning up..."
rm -rf /home/$USER/.afk/
echo "done."