#!/bin/bash
apt=$(command -v apt)

if [ -n "$apt" ]; then
sudo "$apt" install pandoc wkhtmltopdf qrencode
else
echo "an error occured: package manager 'apt' not found in expected location"
echo "please note that this particular setup script is only compatible with Ubuntu and Debian-based distros."
fi
